spring:
  thymeleaf:
    cache: false

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

  datasource:
    url: jdbc:postgresql://localhost:5432/webuni_logisztika
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logisztika:
  delay:
    delay_30_minutes: 5
    delay_60_minutes: 10
    delay_120_minutes: 15